apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: alomra
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nebag/alomra-project-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-port
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
        - name: JWT_SECRET
          value: "Qw8!zP3@kL9vT2$eR7^sN1&bM6*oJ4%uH5"
        - name: EMAIL_USER
          value: "nebag.omar.ensias.itclub@gmail.com"
        - name: EMAIL_PASS
          value: "onhj kjud dymj jxrl"
        - name: NOTIFY_EMAILS
          value: "nebag0s.07@gmail.com,r133319287@um5.ac.ma"
        - name: FRONTEND_URL
          value: "http://localhost:30100"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: alomra
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort 