apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort # Expose le service sur un port de chaque noeud du cluster
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000        # Port du service
      targetPort: 3000  # Port du conteneur
      # Le port externe sera entre 30000-32767. Nous utilisons le 30200 que vous aviez dans votre config CORS
      nodePort: 30200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # REMPLACEZ par le nom de votre image frontend
          image: nebag/alomra-project-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NEXT_PUBLIC_URL