apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: alomra
type: Opaque
data:
  mysql-root-password: T21AcmAwMDM=  # Om@r2003
  mysql-user: cm9vdA==              # root
  mysql-password: T21AcmAwMDM=      # Om@r2003
  mysql-database: YWxvbXJh          # alomra 