name: CI/CD Docker Build & Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (frontend)
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: nebag/alomra-project-frontend:latest

  build-and-push-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (backend)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: nebag/alomra-project-backend:latest
